### ISSUE TITLE
unable to install terraform-docs-v0.6.0-windows-amd64.exe in windows

### ISSUE THREAD

**Issue by narnemanoj** [segmentio/terraform-docs#118]
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

I am trying to install terraform-docs-v0.6.0-windows-amd64.exe in my windows and it's not letting me do that 

#### Actual Behavior

```
I downloaded terraform-docs-v0.6.0-windows-amd64.exe on my windows and double-clicked on it and it's not showing up anything also I tried to run as administrator and even then it's not installing.
```

#### Expected Behavior

```
It should install and I should be able to run terraform docs commands 
```

### Replication Case

1. Download terraform-docs-v0.6.0-windows-amd64.exe
2. Double click/Run as administrator and you will see nothing.
3.Run commands and see whether it's working 

### Version

You can get this information via `terraform-docs --version`.

**Comment by metmajer** [comment]
I am not sure this is a bug, @narnemanoj. terraform-docs does not have an installer. In fact, the binary you have downloaded is the tool that is controlled through a command-line interface. If you double-click it, you effectively invoke terraform-docs without any arguments, which will make it display an overview of the available options. You don´t see anything happening since your double-click doesn’t do anything useful really.

I suggest you try opening a terminal (command prompt) and invoke the downloaded binary there. Keep us posted about the result!

**Comment by metmajer** [comment]
I‘m closing the issue for inactivity.
