### ISSUE TITLE
0.8.0-alpha - poor formatting

### ISSUE THREAD

**Issue by grimm26** [segmentio/terraform-docs#138]
### Prerequisites

Put an `x` into the box that applies:

- [ x] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

I tried out 0.8.0-alpha and the formatting was less than ideal.  The content in the Type and Default columns are wrapped with `code` and `pre` so the rows are *very* long when there are complex types and defaults.  I removed the `pre` tags to avoid this.  I also had a default that was a one element list of "*" which should be escaped.  

The variables file, the original generated md table, and my modified md table are in this gist https://gist.github.com/grimm26/a0ced6cdfb0f8d6ec5377abe2ca5ba3f

### Version
terraform-docs version v0.8.0-alpha darwin/amd64 BuildDate: 2019-12-23T10:16:00-06:00

**Comment by khos2ow** [comment]
Thank you @grimm26 for the feedback, and specially for providing the full config example to work with. I'll take a look later today.

**Comment by khos2ow** [comment]
Sorry for the delayed response. I found something interesting. It seems the issue is not with the way terraform-docs generates the result, rather than the different markdown engines processes them, which unfortunately makes it even harder to solve.

I've used your example config to generate the table output, and

1) VS Code markdown preview mode: shows 100% correct
2) GitLab Markdown engine: shows almost correct
3) GitHub Markdown engine: messes up the content
4) Shoved generated md file into a Hugo site: shows nearly 100% correct

I tried something else to generate fully html based table rather than mixing html tags inside markdown table, which unfortunately didn't make any difference.

So at the moment I'm a bit out of options and trying to understand the difference between these markdown renderer engines. But I wanted to ask you, in the meantime, to give it a try with `markdown document` command (as a test), I know this is inconvenient but it can help narrowing down the issue to only table format and not markdown in general.

**Comment by grimm26** [comment]
@khos2ow I added the output using the document option to my gist.  The result is definitely cleaner, but I'd much rather have a table format.

**Comment by khos2ow** [comment]
@grimm26 yeah I completely understand, I was only trying to see if the issue is within the `markdown` as a whole or it's limited to `markdown table`. I'll try to come up with a fix.

**Comment by khos2ow** [comment]
@grimm26 Can you take a look at this? This seems to be rendered properly.

https://gist.github.com/khos2ow/2dea709aac2b5b3d02198130dc3160e2

I took the same approach as you did, but instead of removing `<pre>` I removed the `<code>` which seems to be the answer. This seems to be fine in at least both GitHub and GitLab.

**Comment by grimm26** [comment]
@khos2ow Yes, that is MUCH better!

**Comment by khos2ow** [comment]
Great, I'm going to open a PR and cut another RC today, please test it out and give us the feedback.

**Comment by khos2ow** [comment]
Feel free to reopen this ticket if you still face the issue after using the `v0.8.0-rc.3`.
