### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by ashkanr** [segmentio/terraform-docs#14]
Hi, thanks for useful tool. Would you please consider porting it to Homebrew systems also?

Best regards,

**Comment by yields** [comment]
hey there, [binaries](https://github.com/segmentio/terraform-docs/releases) are the way to go, i don't use brew and not familiar with it, sorry!

**Comment by metmajer** [comment]
@ashkrosh our project now contains a `HomebrewFormula/terraform-docs.rb`. This file will be updated with each new release of `terraform-docs` and will be contributed to the upstream github.com/Homebrew/homebrew-core` repository. Since today, we have v0.4.5 available as a release and available via `brew`. Have fun! :)
