### ISSUE TITLE
use semver versioning?

### ISSUE THREAD

**Issue by tbugfinder** [segmentio/terraform-docs#152]
### Prerequisites

Put an `x` into the box that applies:

- [X] This issue describes a question.
- [ ] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

I'm wondering if this project would benefit from semantic versioning and therefore v0.8.0 would rather be a v1.0.0 as breaking changes are targeted.

[Changelog](https://github.com/segmentio/terraform-docs/blob/master/CHANGELOG.md#unreleased)

[https://semver.org](https://semver.org)

#### Actual Behavior

Briefly describe what happened.

```
N/A
```

Do you have long logs to share? Please go to https://ghostbin.com and insert the link here.

#### Expected Behavior

Briefly describe what you expected to happen.

```
N/A
```

### Replication Case

Tell us which steps to take to replicate your problem.

N/A

### Version

You can get this information via `terraform-docs --version`.

v0.8.0-rc1

**Comment by khos2ow** [comment]
Thanks for the feedback, we're definitely following the semver version. The reason for considering v0.8.0 over v1.0.0 for the next release is that we're still not fully satisfied with the state and maturity of the `terraform-docs` as a binary. We're going on v1 most probably the immediate release after [v0.9.0](https://github.com/segmentio/terraform-docs/milestone/2).

SemVer [specification](https://semver.org/#spec-item-4) says

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

There's actually no promise of backward compatibility when major version is `0`, but we're trying hard to be backward compatible nevertheless.

The current release is very special because of its magnitude of changes that went into it and except two flags rename/removal and change case of JSON object (to be more normalized) we're not expecting any backward incompatibility (which is a huge deal considering we've originally decided to drop the support for module comment and resource comments).

I hope that answers your question, otherwise please let us know.

**Comment by tbugfinder** [comment]
Thanks for clarification.
