### ISSUE TITLE
Missing list bullets and extra end of line whitespace

### ISSUE THREAD

**Issue by chrisgilmerproj** [segmentio/terraform-docs#178]
### Prerequisites

- [x] This issue describes a bug.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

There are two small issues with terraform-docs in v0.8.1. 

- In markdown lists that start with `*` instead of `-` the `*` character is removed in the `README.md`
- For lists that are copied from `main.tf` whitespace characters are added to the end of the list item in the `README.md`

#### Actual Behavior

A good example is this:

In `main.tf`

```
/*
 * Creates the following resources:
 *
 * * RDS Instance (PostgreSQL).
 * * Security Group allowing access from ECS.
 * * Task Definition for DB migrations.
 * * Lambda function for cleaning up manual snapshots.
 * * CloudWatch Alarms on CPU credits and Free Storage.
 * * RDS event notification sending to an SNS topic.
 *
 */
```

Results in `README.md` (with spaces after each list indicated by `_`):

```
Creates the following resources:

 RDS Instance (PostgreSQL).__
 Security Group allowing access from ECS.__
 Task Definition for DB migrations.__
 Lambda function for cleaning up manual snapshots.__
 CloudWatch Alarms on CPU credits and Free Storage.__
 RDS event notification sending to an SNS topic.
```

Importantly: It does not add whitespace at the end of the last list item. Also, changing the `*` to `-` works but the whitespace problem still persists. For instance the bullets persist if I do this:

In `main.tf`

```
/*
 * Creates the following resources:
 *
 * - RDS Instance (PostgreSQL).
 * - Security Group allowing access from ECS.
 * - Task Definition for DB migrations.
 * - Lambda function for cleaning up manual snapshots.
 * - CloudWatch Alarms on CPU credits and Free Storage.
 * - RDS event notification sending to an SNS topic.
 *
 */
```

Resulting in `README.md` (with spaces after each list indicated by `_`):

```
Creates the following resources:

- RDS Instance (PostgreSQL).__
- Security Group allowing access from ECS.__
- Task Definition for DB migrations.__
- Lambda function for cleaning up manual snapshots.__
- CloudWatch Alarms on CPU credits and Free Storage.__
- RDS event notification sending to an SNS topic.
```

Can I provide logs that would help here?

#### Expected Behavior

I expect that I could use either `*` or `-` for lists. I also expect no whitespace at the end of lines.

### Replication Case

To replicate try to use the details above, I've tried to be as complete as possible but can also send you more if you request.

### Version

You can get this information via `terraform-docs --version`.

```sh
terraform-docs version v0.0.0- v0.8.1 darwin/amd64 BuildDate: 2020-01-21T18:58:28+0000
```

**Comment by khos2ow** [comment]
Thanks @chrisgilmerproj , use of `*` as bullet list wasn't included in parsing and normalizing the content, I'm gonna add it soon.

But the extra double space at the end of lines is by design, although in this particular case I understand where you're coming from but consider this example:

```
/**
 * Lorem ipsum dolor sit amet,
 * consectetur adipiscing elit, sed
 * do eiusmod tempor incididunt ut
 * labore et dolore magna aliqua
 */
```

the expected rendered result would be:

```
Lorem ipsum dolor sit amet,
consectetur adipiscing elit, sed
do eiusmod tempor incididunt ut
labore et dolore magna aliqua
```

but without extra spaces it would actually get rendered as:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
```

This is the normal behavior of multi-lines paragraph in Markdown, which in this case I have no solution for yet.

Also if we try to add the `__` at the end of each line (irrelevant of being a list or not), this would be the result, **without double spaces**:

* Lorem ipsum dolor sit amet,
* consectetur adipiscing elit, sed
* do eiusmod tempor incididunt ut
* labore et dolore magna aliqua

**with double spaces**:

* Lorem ipsum dolor sit amet,  
* consectetur adipiscing elit, sed  
* do eiusmod tempor incididunt ut  
* labore et dolore magna aliqua  

I don't see any difference between the two, is this something acceptable to you?

**Comment by chrisgilmerproj** [comment]
@khos2ow - thank you for the detailed information about the behavior! 

So the issue with the double spaces in the list is that I also run a pre-commit hook that strips additional whitespace from lines. The effect is that terraform-docs adds whitespace to the end of the list items which causes the whitespace rule to fail. The whitespace pre-commit tries to fix the error by removing the extra whitespace but on a subsequent run of pre-commit the terraform-docs rule adds them back. So I end up in an endless cycle.

What I'd love is if the whitespace was stripped from the end of the list items for me. Then both the rules could run and pass for my commits. So while I see that the rendering isn't affected by the whitespace it conflicts with our repository rule to remove all that extra whitespace where it finds it.

Do you have alternatives? Or is it possible we could pass in a flag that would enable or disable that behavior so I could make it work just for my repo?

**Comment by khos2ow** [comment]
I've actually found a way to make the `__` work. Basically the double spaces will be appended at the end of all lines *which* they immediately are followed by another line (the behavior of a paragraph). But for example in your case, where lines are, indeed, followed by another lines, this won't get applied because the follower lines do start with special characters (which is not a paragraph behavior).

**Comment by chrisgilmerproj** [comment]
That's great news! Thank you very much!
