### ISSUE TITLE
comments are injected as variable description

### ISSUE THREAD

**Issue by tbugfinder** [segmentio/terraform-docs#187]
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a bug or is a question
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

If comments are before a variable definition, then those are added as the variable description.

#### Actual Behavior

Briefly describe what happened.

variables.tf
```
# let's see where this comment goes.
variable "objecttypewithdefaults" {
  type = object({
    location           = string
    storage_class      = string
    versioning_enabled = bool
    bucket_policy_only = bool
    lifecycle_rules = map(object({
      action = map(string)
      condition = object({
        age                   = number
        with_state            = string
        created_before        = string
        matches_storage_class = list(string)
        num_newer_versions    = number
      })
    }))
  })

  default = {
    location           = "europe-west4"
    storage_class      = "REGIONAL"
    versioning_enabled = true
    bucket_policy_only = true
    lifecycle_rules    = {}
  }
}

```
`terraform-docs json .` creates the following output (snippet):
```
    {
      "name": "objecttypewithdefaults",
      "type": "object({\n    location           = string\n    storage_class      = string\n    versioning_enabled = bool\n    bucket_policy_only = bool\n    l
ifecycle_rules = map(object({\n      action = map(string)\n      condition = object({\n        age                   = number\n        with_state            =
 string\n        created_before        = string\n        matches_storage_class = list(string)\n        num_newer_versions    = number\n      })\n    }))\n  })
",
      "description": "let's see where this comment goes.",
      "default": {
        "bucket_policy_only": true,
        "lifecycle_rules": {},
        "location": "europe-west4",
        "storage_class": "REGIONAL",
        "versioning_enabled": true
      }
    },
```
If the variable - description is set, it isn't replaced, which is good.

#### Expected Behavior

Either this should be part of the documentation or the description shouldn't be fed by a comment before the variable.

Either it should be documented or the description should not be built by a comment before the variable definition.
```

```

### Replication Case

Tell us which steps to take to replicate your problem.

1. use above variables.tf
1. execute `terraform-docs json .`

### Version

You can get this information via `terraform-docs --version`.
terraform-docs version v0.8.1 e7ad477 linux/amd64 BuildDate: 2020-01-21T15:49:11+0000

**Comment by khos2ow** [comment]
This has always been like this, as a matter or fact this was one of the hardest thing we had to solve for while adding the support for Terraform 0.12 in version v0.8.0. There were a lot of discussion and we actually ended up deciding to drop the support for this feature (https://github.com/segmentio/terraform-docs/issues/62#issuecomment-507069369 , https://github.com/hashicorp/terraform-config-inspect/issues/21#issuecomment-525259471) but we ended up finding a way to still support this in #151.

As you mentioned, if the `description` property is explicitly set in the `variable` or `output`, leading comment will be ignored otherwise it's going to be attempted to extract _description_ from leading comment. The supported formats are 1) `#` and 2) `//`.

In your case what can be done is either:

- put an extra line between comment and resource definition. To be honest this is very annoying as the comments look to be dangling, but still it's an option.
  ```
  # leading comment on a resource which
  # doesn't get extracted as an description
  # because of extra space between this and
  # definition of the _variable_

  variable "something" {
  ...
  ```
- or better approach is that you can use `/** one or multi lines **/` leading comment
  ```
  /** leading jsdoc comment on a resource, gets ignored **/
  variable "something" {
  }

  /**
   * leading jsdoc comment on a resource which
   * doesn't get extracted as an description
   */
  variable "something" {
  }
  ```

**Comment by tbugfinder** [comment]
Thanks for the update @khos2ow . Just wondering if this feature or above details should be added to the documentation.

**Comment by khos2ow** [comment]
Yes definitely, I've recently created [docs](https://github.com/segmentio/terraform-docs/tree/master/docs) folder to capture all these documentation, and we should ramp it up.

I'm closing this issue now, if you still have some issue please reopen this or new one.
