### ISSUE TITLE
Column Description not correctly filled

### ISSUE THREAD

**Issue by eservent** [segmentio/terraform-docs#237]
### Prerequisites

Put an `x` into the box that applies:

- [x ] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

I have some variables with no description parameter (or empty, like "")
If before the variable, I wrote some comments, then in the documentation (markdown), the comments are present in the description column.

#### Actual Behavior

Briefly describe what happened.

```
##############
#
# DMS
#
##############
variable "dms_enable_validation" {
  type    = bool
  default = false
}
```
Results in doc.md
```
| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| dms\_enable\_validation | ###############  DMS  ############### | `bool` | `false` | no |
| 
```
Do you have long logs to share? Please go to https://ghostbin.com and insert the link here.

#### Expected Behavior

Briefly describe what you expected to happen.

```
Empty Description column (or N/A). Comments don't need to appear in documentation.
```
### Version
0.8.2
0.9.1

You can get this information via `terraform-docs --version`.

**Comment by khos2ow** [comment]
This is a feature and by design it works as intended. We're processing leading comments of a `variable` or `output` as a potential "description", although there are two approaches you can take to make those leading comments not being processed as a "description". You can check #151 for a bit more information.

1. Put an extra line space between the comment and the resource. To be honest this is not the best approach as the comments seem to be dangling.
    ```
    ##############
    #
    # DMS
    #
    ##############

    variable "dms_enable_validation" {
      type    = bool
      default = false
    }
    ```

2. The better approach is to use `/** javadoc style comment **/`. This style of commenting is ignored by the `terraform-docs` engine.
    ```
    /***********************
     *
     * DMS
     *
     ***********************/
    variable "dms_enable_validation" {
      type    = bool
      default = false
    }
    ```

**Comment by eservent** [comment]
Thank you for your explanation. I had a doubt that it was a bug or a feature.
Thanks for all.
Emmanuel.
