### ISSUE TITLE
"invalid syntax" error when output name is not quoted

### ISSUE THREAD

**Issue by beatcracker** [segmentio/terraform-docs#64]
### Prerequisites

- [x] This issue describes a bug.
- [ ] This issue describes a feature request.

### Description

I get `invalid syntax` error when output name is not quoted in `tf` file.

```
> terraform-docs md .\foobar\outputs.tf
2018/09/25 18:53:54 invalid syntax
```

### Replication Case

Create `output.tf` where output names are not quoted.

* Example, no quotes around `disk_size`:

```terraform
output disk_size {
  value  = "${var.disk_size}"
}
```

### Version

`0.4.0`, `windows-amd64`

### Notes
Affects variables too.

**Comment by metmajer** [comment]
Hi @beatcracker and thank you for reporting this issue!

I have already analyzed the error and found the issue to be located in [doc.go#L222-L225](https://github.com/segmentio/terraform-docs/blob/master/internal/pkg/doc/doc.go#L222-L225). Here, `strconv.Unquote` produces the error since the name does not contain quotes.

Would you be interested in submitting a fix? Should be easy and I can assist you with your contribution.

**Comment by beatcracker** [comment]
Yep, looks easy. Basically we can just ignore `strconv.Unquote` error and return original string if it's already unquoted, right?
