### ISSUE TITLE
terraform-docs --version output (dev build) #86

### ISSUE THREAD

**Issue by tbugfinder** [segmentio/terraform-docs#88]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description
This is a follow up to #86 . As it is not possible to reopen an issue.

Execution of `terraform-docs --version` on Linux only outputs `dev` if it was installed using the given `go get` command.

#### Actual Behavior

Output:

```
# terraform-docs --version
dev

```

Do you have long logs to share? Please go to https://ghostbin.com and insert the link here.

#### Expected Behavior

Expected output is more than just `dev`. E.g. a string including a build date. "Old" dev builds might be used to e.g. create bug reports without being able to refer to the installed version.
```
dev (build dd-mm-yyyy HH:mm)
```

### Replication Case

Tell us which steps to take to replicate your problem.

1. go get -v github.com/segmentio/terraform-docs
2. terraform-docs --version

### Version

You can get this information via `terraform-docs --version`.
dev
Whichever dev build it might be.

**Comment by metmajer** [comment]
Hi @tbugfinder. While a date is nice to have, it is as well ambiguous. Since `go get` builds the application using `go install`, the same Git revision could end up with several different dates on different machines depending on when they were `go get`ted.

As a better solution, I suggest an implementation based on `git rev-parse --short HEAD`. Given the following `git log`, `git rev-parse --short HEAD` would return `fc78765`, which is unambiguous and allows the user to determine, which revision he or she is currently using:

```
commit fc787659af7d1db62df9a59a96040698521e4e93 (HEAD -> update-docopt-go, origin/update-docopt-go)
Author: Martin Etmajer <metmajer@getcloudnative.io>
Date:   Mon Nov 19 20:36:46 2018 +0100

    Update docopt github.com/docopt/docopt.go's latest rev.
...
```

When `terraform-docs` has been installed via `go get`, it will yield:

```
$ terraform-docs --version
rev-fc78765
```

Unless it has been built via `make build`, such as the `terraform-docs` releases, which would yield:

```
$ terraform-docs --version
v0.5.0
```

Sounds like a plan?

**Comment by tbugfinder** [comment]
Initially I didn't think about getting the same result of equal `go get` builds, however your idea makes sense to me. For a user `rev-fc78765` might not have any meaning but it helps to track the builds.

**Comment by tbugfinder** [comment]
I do also see other projects maintaining releases within the master branch and developing in feature branches - do you see that as a go paradigm?

**Comment by metmajer** [comment]
It's not really a go paradigm. It's just the way you need to do things if you don't contributors to have write access to the master branch.

**Comment by khos2ow** [comment]
@metmajer I already have a branch ready for this but it depends on using `-ldflags` which was enhanced in #115 . If we can proceed with that PR I'll be open another PR to fix the version issue.

**Comment by eredi93** [comment]
@khos2ow it looks like your change https://github.com/terraform-docs/terraform-docs/pull/115 is adding `v0.0.0-` on the version command when terraform-docs is installed using `brew`

```
$ terraform-docs version
terraform-docs version v0.0.0- v0.10.1 darwin/amd64 BuildDate: 2020-09-29T01:18:38+0100
```

is this expected? should i open a separate issue?

**Comment by khos2ow** [comment]
Have you installed this with `brew` or just downloaded the standalone released binary? Because once - on a colleague's laptop - I noticed this while they had installed it with brew, and when we manually downloaded the binary it wasn't like that.

If you verify this and the issue was still there, yes please open a new issue.

**Comment by khos2ow** [comment]
@eredi93 yes please open a new issue.
