### ISSUE TITLE
Unify behavior of empty Description among different print types

### ISSUE THREAD

**Issue by khos2ow** [segmentio/terraform-docs#92]
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Following up a discussion in #81 the behavior of _empty_ `Description` needs to be unified between different `print` types. Considering:

- `json`: technically can be remained as empty since empty JSON attribute is meaningful
- `markdown`: one of the following for both `table` and `document`
  - `Description: -`
  - `Description: n/a`
  - `Description: ""`
  - hide `Description` altogether

**Comment by metmajer** [comment]
I would make the difference between a non-existent description and a description which is an empty string explicit. Since a description is not a value type, I would take a different approach than in #93:

##### No description provided

- with `table`: n/a
- with `document`: Description: n/a

##### Description provided

###### Description is an empty string

- with `table`, print nothing (not `""`, since this would be useful with a value type), since here we literally have no information
- with `document`: Description: 

###### Description is not an empty string

Obvious.

**Comment by metmajer** [comment]
Reconsidering my thoughts from earlier today, I would say that, for the end-user it only really matters if a description is there or not, and not whether it's an empty string or not provided at all. Therefore:

##### No description provided

- with `table`:
- with `document`: Description: 

##### Description provided

###### Description is an empty string

- with `table`:
- with `document`: Description: 

###### Description is not an empty string

Obvious.
